<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class ConvertResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'currency_from' => $this->currency_from,
            'currency_to' => $this->currency_to,
            'value' => $this->value,
            'converted_value' => $this->converted_value,
            'rate' => $this->rate,
            'created_at' => $this->created_at->format('Y-m-d H:i:s')
        ];
    }

    public function withResponse($request, $response)
    {
        $response->setStatusCode(200);
        parent::withResponse($request, $response); // TODO: Change the autogenerated stub
    }
}
