<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\ResourceCollection;

class CurrencyCollection extends ResourceCollection
{
    /**
     * Transform the resource collection into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        $result = [];
        foreach ($this->collection as $c){
            $result[$c->currency] = $c->value;
        }
        return $result;
    }

    public function withResponse($request, $response)
    {
        $response->setStatusCode(200);
        parent::withResponse($request, $response); // TODO: Change the autogenerated stub
    }
}
